POST http://localhost:5000/signin
content-type: application/json

{
  "username": "lenaa",
  "password": "yeehaw",
  "email": "lena@aaf.com"
}

###

POST http://localhost:5000/plan/create
content-type: application/json

{
  "planName": "hello",
  "category": "running",
  "numDays": 5,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZWNmNTA3ZDRhOTBiMTA5YjhkZjBkM2RhMjE5YmNiYiIsImlhdCI6MTY0NTg1MTc4NSwiZXhwIjoxNjQ4NDQzNzg1fQ.G9LyXSB6icBhU5hcQdPiRUIHphCSO8Wo7Cti4D5NyLk"
}