POST http://localhost:5000/signin
content-type: application/json

{
  "username": "tyson",
  "password": "yeehaw",
  "email": "tyson@tyson.com"
}

###

POST http://localhost:5000/plan/create
content-type: application/json

{
  "planName": "hello",
  "category": "running",
  "numDays": 5,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0eXNvbiIsImlhdCI6MTY0NTYxNzU4MywiZXhwIjoxNjQ4MjA5NTgzfQ.VUwLfrEuBVu7p3yHsiuv8WiN_1pmLI2yEbv2Jz52vNw"
}